name: Sync para Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push para Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git push  https://danielmischiatti:$HF_TOKEN@huggingface.co/spaces/danielmischiatti/transcricao-whisper main --force
